---
collections:
  - name: google.cloud
    version: 1.1.2
  - name: amazon.aws
    version: 5.4.0
  - name: containers.podman
  - name: ansible.utils
  - name: community.general
    version: 6.2.0
  - name: redhat.ansible_on_clouds

    