---

argument_specs:
  main:
    # Create a multline string that creates a list of strings
    description:
      - |
        Performs the backup of AAP on AWS.

      - |
        Inputs example

        1. Set your input variables:

        ::

          # ./inputs/vars.yaml
          #
          # AoC AWS: Backup vars
          ---

          aws_foundation_stack_name: "aoc-prod"
          aws_region: us-east-1
          aws_backup_vault_name: "aoc-prod-backup-vault"
          aws_backup_iam_role_arn: "aoc-prod-filestore-backup"

        2. Run the command:

        ::
          ansible-playbook -e @inputs/vars.yaml redhat.ansible_on_clouds.standalone_aws_backup
      - |-
        *Authors*

        - Pratyush Bhandari (@pratyush-bhandari)
        - Zack Kayyali (@zack-kayyali)

    short_description: Performs the backup of AAP on AWS.
    options:
      aws_foundation_stack_name:
        description: AoC AWS deployment name
        type: "str"
        required: True
      aws_region:
        description: AWS compute region
        type: "str"
        required: True
      aws_backup_vault_name:
        description: Name of the AWS backup vault for EFS backups
        type: "str"
        required: True
      aws_backup_iam_role_arn:
        description: ARN (Amazon Resource Name) for backup role on AWS.
        type: "str"
        required: True
      backup_prefix:
        description: The prefix to add to the backup name <backup_prefix>-<deployment_name>-<timestamp>
        type: "str"
        default: "aoc-backup"
      aws_s3_bucket:
        type: "str"
        required: True
        description: "AWS S3 bucket used to store backup data"
      aws_ssm_bucket_name:
        type: "str"
        required: True
        description: "A valid s3 bucket. Used for SSM connections"