---

- name: Set main vars
  ansible.builtin.set_fact:
    # Hardcoded value for the first version
    aws_first_version_hardcoded: "2.2.20221201-00"
    # Set list of asserts for SSM usage
    # reused in multiple tasks
    aws_ssm_input_asserts:
      - ansible_aws_ssm_bucket_name is defined
      - ansible_aws_ssm_bucket_name is not none
      - ansible_aws_ssm_bucket_name | length > 0
      - ansible_aws_ssm_region is defined
      - ansible_aws_ssm_region is not none
      - ansible_aws_ssm_region | length > 0
      - ansible_connection == 'aws_ssm'
      - ansible_aws_ssm_s3_addressing_style == 'virtual'
