# aws_remove_extension_nodes

# This playbook is used to deploy the AoC Self-managed AWS environment from source.
#
# Input variables:
# aws_foundation_stack_name: ""                 # Name of CloudFormation AAP foundation stack
# aws_region: ""                                # Name of AWS region
# aws_launch_template_name: ""                  # The name of the AWS EC2 launch template to create
# aws_autoscaling_group_name: ""                # The name of the AWS AutoScaling Group to create for the extension nodes

---

- name: AWS remove extension nodes
  hosts: localhost
  connection: local
  vars:
    # Default values
  tasks:
    - name: Check Operations images and Ansible on Cloud deployment versions
      ansible.builtin.include_role:
        name: redhat.ansible_on_clouds.helpers.standalone_check_aoc_version
        apply:
          vars:
            ansible_connection: "aws_ssm"
            ansible_aws_ssm_bucket_name: "{{ aws_ssm_bucket_name }}"
            ansible_aws_ssm_region: "{{ aws_region }}"
            ansible_aws_ssm_s3_addressing_style: "virtual"
            ansible_python_interpreter: /usr/bin/python3
            hubs: "{{ groups['aap_hubs'] }}"
            filesystem: "/efs"

    - name: "Load 'auth' task file"
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/../roles/standalone_aws_core_dev/tasks/auth.yaml"

    - name: "Run Remove Extension Nodes Role"
      ansible.builtin.include_role:
        name: redhat.ansible_on_clouds.standalone_aws_remove_extension_nodes
