# aws_backup_stack.yaml

# This playbook is used to backup the AoC Self-managed AWS environment.
#
# Input variables:
#     aws_foundation_stack_name: ""                            # AAP foundation stack name
#     aws_region: us-east-1                                    # AWS region
#     aws_backup_vault_name: ""                                # AWS backup vault name. If left empty, EFS backup will be skipped. ex - aws/efs/automatic-backup-vault
#     aws_backup_iam_role_arn: ""                              # AWS backup role name. Must be set if backing up EFS. ex - arn:aws:iam::<Account-ID>:role/service-role/AWSBackupDefaultServiceRole

# ---

- name: AWS backup AAP foundation stack
  hosts: localhost
  connection: local
  tasks:
    - name: Check Operations images and Ansible on Cloud deployment version
      ansible.builtin.include_role:
        name: redhat.ansible_on_clouds.helpers.standalone_check_aoc_version
        apply:
          vars:
            ansible_connection: "aws_ssm"
            ansible_aws_ssm_bucket_name: "{{ aws_ssm_bucket_name }}"
            ansible_aws_ssm_region: "{{ aws_region }}"
            ansible_aws_ssm_s3_addressing_style: "virtual"
            ansible_python_interpreter: /usr/bin/python3
            hubs: "{{ groups['aap_hubs'] }}"
            filesystem: "/efs"

    - name: "Load 'auth' task file"
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/../roles/standalone_aws_core_dev/tasks/auth.yaml"

    - name: "Run AWS Backup Role"
      ansible.builtin.include_role:
        name: redhat.ansible_on_clouds.standalone_aws_backup
