# aws_deploy_extension_nodes
#
# The following parameters are required:
# - aws_launch_template_name
# - aws_autoscaling_group_name

# The following variables will be populated:
# - aws_instance_type
# - aws_asg_max_size

---

- name: "[remove_extension_nodes] Remove extension nodes"
  block:
    - name: "[remove_extension_nodes] Assert vars are defined"
      loop:
        - aws_launch_template_name
        - aws_autoscaling_group_name
        - aws_region
      ansible.builtin.assert:
        that: 
          - "{{ item }} is defined"
          - "{{ item }} != ''"
        msg: "Variable {{ item }} is not defined"

    - name: "Configure default region"
      ansible.builtin.shell:
        cmd: aws configure set region "{{ aws_region }}"
    
    - name: Remove extension node autoscaling group
      amazon.aws.autoscaling_group:
        name: "{{ aws_autoscaling_group_name }}"
        state: absent
    
    - name: Remove launch template
      community.aws.ec2_launch_template:
        name: "{{ aws_launch_template_name }}"
        state: absent